name: Release Go project
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache: true
          cache-dependency-path: "**/go.sum"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
